[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.obj.leads"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot","crm","objects","leads"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.leads"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
